# create a tensor

In [1]:
import torch

In [2]:
a = torch.empty(1)

In [3]:
a

tensor([3.2115e-16])

In [4]:
b = torch.empty(2)

In [6]:
b.size()

torch.Size([2])

In [7]:
b

tensor([8.2537e+07, 4.3461e-41])

In [8]:
c = torch.empty(3, 4)

In [9]:
c

tensor([[ 8.2537e+07,  4.3461e-41,  8.2537e+07,  4.3461e-41],
        [ 4.4842e-44,  0.0000e+00,  8.9683e-44,  0.0000e+00],
        [-6.2517e+21,  3.1763e-41,  3.8495e-37,  6.1590e-36]])

In [10]:
c.ndimension()

2

In [11]:
d = torch.empty(3, 4, 5)

In [12]:
d

tensor([[[ 8.2540e+07,  4.3461e-41,  8.2540e+07,  4.3461e-41,  0.0000e+00],
         [ 0.0000e+00,  5.6192e-43,  0.0000e+00,  8.2539e+07,  4.3461e-41],
         [ 8.2539e+07,  4.3461e-41,  1.2766e+23,  3.1767e-41,  3.2230e-44],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,         nan,         nan]],

        [[ 0.0000e+00,  0.0000e+00,  9.1084e-44,  0.0000e+00,  2.7594e+26],
         [ 3.1767e-41,  2.5119e+26,  3.1767e-41,  0.0000e+00,  4.3461e-41],
         [ 4.6243e-44,  0.0000e+00,  2.7593e+26,  3.1767e-41,  4.0498e-43],
         [ 0.0000e+00,  2.7594e+26,  3.1767e-41,  2.7597e+26,  3.1767e-41]],

        [[-6.2512e+21,  3.1763e-41,  2.0179e-43,  0.0000e+00,  1.2612e-44],
         [ 0.0000e+00,  4.6243e-44,  0.0000e+00,  2.7594e+26,  3.1767e-41],
         [ 2.5118e+26,  3.1767e-41,  1.1210e-43,  0.0000e+00,  8.9683e-44],
         [ 0.0000e+00, -6.2395e+21,  3.1763e-41,  2.4803e-43,  0.0000e+00]]])

In [13]:
d.dtype

torch.float32

In [14]:
type(d)

torch.Tensor

In [15]:
a = torch.ones(2, 3)

In [16]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
b = torch.zeros(2, 3)

In [19]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
a = torch.rand(1, 2)

In [21]:
a

tensor([[0.1450, 0.6268]])

In [22]:
a.shape

torch.Size([1, 2])

In [23]:
a.size()

torch.Size([1, 2])

In [24]:
a = torch.rand(3, 4, 5)

In [25]:
a

tensor([[[0.6093, 0.6330, 0.6190, 0.9429, 0.7606],
         [0.1571, 0.7758, 0.1845, 0.5935, 0.2455],
         [0.7339, 0.2681, 0.9784, 0.6048, 0.3389],
         [0.6533, 0.3006, 0.5814, 0.3362, 0.9234]],

        [[0.8530, 0.1225, 0.8254, 0.8554, 0.4852],
         [0.8561, 0.3035, 0.3434, 0.2474, 0.9169],
         [0.8077, 0.9385, 0.6615, 0.8194, 0.4384],
         [0.3519, 0.6251, 0.6423, 0.0192, 0.0276]],

        [[0.0338, 0.0875, 0.9720, 0.1633, 0.3446],
         [0.6810, 0.1053, 0.9590, 0.1909, 0.1166],
         [0.8150, 0.5923, 0.1616, 0.4174, 0.3170],
         [0.2774, 0.9883, 0.4596, 0.1193, 0.4980]]])

In [30]:
a = torch.tensor([1., 2., 3., 4.])

In [31]:
a

tensor([1., 2., 3., 4.])

In [32]:
a.dtype

torch.float32

In [33]:
a = torch.tensor([[1., 2., 3., 4.], [2.,3.,4.,4.], [4., 5., 6., 7.]])

In [34]:
a

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 4.],
        [4., 5., 6., 7.]])

In [36]:
a = torch.tensor([[[1., 2., 3., 4.], [2.,3.,4.,4.], [4., 5., 6., 7.]], [[1., 2., 3., 4.], [2.,3.,4.,4.], [4., 5., 6., 7.]]])

In [37]:
a

tensor([[[1., 2., 3., 4.],
         [2., 3., 4., 4.],
         [4., 5., 6., 7.]],

        [[1., 2., 3., 4.],
         [2., 3., 4., 4.],
         [4., 5., 6., 7.]]])

In [38]:
a.dtype

torch.float32

In [40]:
a = torch.ones(1, dtype=torch.float16)

In [41]:
a

tensor([1.], dtype=torch.float16)

In [42]:
a.shape

torch.Size([1])

In [43]:
a = torch.ones(1, dtype=torch.double)

In [44]:
a.dtype

torch.float64

In [45]:
a = torch.ones(1, dtype=torch.int16)

In [46]:
a.dtype

torch.int16

In [47]:
# reshape a tensor

# reshape a tensor

In [48]:
a = torch.rand(3,4)

In [49]:
a

tensor([[0.5254, 0.3421, 0.1909, 0.1007],
        [0.8193, 0.4263, 0.4578, 0.6118],
        [0.0434, 0.6322, 0.4326, 0.9391]])

In [50]:
a = a.view(6,2)

In [51]:
a

tensor([[0.5254, 0.3421],
        [0.1909, 0.1007],
        [0.8193, 0.4263],
        [0.4578, 0.6118],
        [0.0434, 0.6322],
        [0.4326, 0.9391]])

In [53]:
a = a.reshape(4,3)

In [54]:
a

tensor([[0.5254, 0.3421, 0.1909],
        [0.1007, 0.8193, 0.4263],
        [0.4578, 0.6118, 0.0434],
        [0.6322, 0.4326, 0.9391]])

In [55]:
a = a.view(1, 12)

In [56]:
a

tensor([[0.5254, 0.3421, 0.1909, 0.1007, 0.8193, 0.4263, 0.4578, 0.6118, 0.0434,
         0.6322, 0.4326, 0.9391]])

In [57]:
a = a.view(12, 1)

In [58]:
a

tensor([[0.5254],
        [0.3421],
        [0.1909],
        [0.1007],
        [0.8193],
        [0.4263],
        [0.4578],
        [0.6118],
        [0.0434],
        [0.6322],
        [0.4326],
        [0.9391]])

In [59]:
a = a.view(10, 2)

RuntimeError: shape '[10, 2]' is invalid for input of size 12

# convert a tensor into numpy

In [84]:
a = torch.rand(4,3)

In [85]:
a.dtype

torch.float32

In [86]:
type(a)

torch.Tensor

In [87]:
b=a.numpy()

In [88]:
type(b)

numpy.ndarray

In [89]:
b.dtype

dtype('float32')

In [90]:
b

array([[0.89853686, 0.0441646 , 0.50996804],
       [0.63487834, 0.47679526, 0.19076031],
       [0.00910217, 0.8741417 , 0.15490621],
       [0.20952094, 0.53824496, 0.8886824 ]], dtype=float32)

In [91]:
b[0][0]=1.0

In [92]:
b

array([[1.        , 0.0441646 , 0.50996804],
       [0.63487834, 0.47679526, 0.19076031],
       [0.00910217, 0.8741417 , 0.15490621],
       [0.20952094, 0.53824496, 0.8886824 ]], dtype=float32)

In [93]:
a

tensor([[1.0000, 0.0442, 0.5100],
        [0.6349, 0.4768, 0.1908],
        [0.0091, 0.8741, 0.1549],
        [0.2095, 0.5382, 0.8887]])

In [94]:
a.device

device(type='cpu')

# convert numpy into tensor

In [95]:
# as_tensor()
# from_numpy()

import numpy as np

In [96]:
num_a = np.array([1,2, 3])

In [97]:
type(num_a)

numpy.ndarray

In [98]:
num_a.dtype

dtype('int64')

In [99]:
a = torch.as_tensor(num_a.astype(np.float16))

In [100]:
a

tensor([1., 2., 3.], dtype=torch.float16)

In [101]:
type(a)

torch.Tensor

In [102]:
a.dtype

torch.float16

In [103]:
a1 = np.array([1,3,4])

In [104]:
a1

array([1, 3, 4])

In [105]:
type(a1)

numpy.ndarray

In [106]:
a11 = torch.from_numpy(a1.astype(np.float32))

In [107]:
a11

tensor([1., 3., 4.])

In [108]:
type(a11)

torch.Tensor

# slicing

In [109]:
a = torch.rand(4, 5)

In [110]:
a

tensor([[0.5947, 0.8824, 0.6633, 0.0398, 0.3222],
        [0.0829, 0.0824, 0.6629, 0.8239, 0.4301],
        [0.4162, 0.7011, 0.2226, 0.1832, 0.3354],
        [0.5333, 0.0575, 0.3737, 0.7059, 0.2949]])

In [111]:
a[:,1:]

tensor([[0.8824, 0.6633, 0.0398, 0.3222],
        [0.0824, 0.6629, 0.8239, 0.4301],
        [0.7011, 0.2226, 0.1832, 0.3354],
        [0.0575, 0.3737, 0.7059, 0.2949]])

In [113]:
a[1:3, :]

tensor([[0.0829, 0.0824, 0.6629, 0.8239, 0.4301],
        [0.4162, 0.7011, 0.2226, 0.1832, 0.3354]])

# stack and concatenate

In [114]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2226, 0.2232, 0.3141],
        [0.4741, 0.8182, 0.3392]])
tensor([[0.3136, 0.3919, 0.9276],
        [0.9008, 0.6239, 0.8552]])


In [117]:
a.shape

torch.Size([2, 3])

In [118]:
b.shape

torch.Size([2, 3])

In [115]:
c = torch.stack([a, b], axis=0)

In [116]:
c

tensor([[[0.2226, 0.2232, 0.3141],
         [0.4741, 0.8182, 0.3392]],

        [[0.3136, 0.3919, 0.9276],
         [0.9008, 0.6239, 0.8552]]])

In [119]:
c.shape

torch.Size([2, 2, 3])

In [120]:
a = torch.rand(2,3)
b = torch.rand(2,3)


In [121]:
print(a.shape, b.shape)

torch.Size([2, 3]) torch.Size([2, 3])


In [122]:
c = torch.cat([a, b], axis=0)

In [123]:
c

tensor([[0.0684, 0.3975, 0.8350],
        [0.4554, 0.6882, 0.3839],
        [0.9375, 0.5018, 0.5122],
        [0.0952, 0.6670, 0.5744]])

In [124]:
c.shape

torch.Size([4, 3])

In [125]:
d = torch.rand(5, 3)

In [126]:
d

tensor([[0.5799, 0.9837, 0.3657],
        [0.7752, 0.7997, 0.9014],
        [0.7895, 0.8903, 0.5997],
        [0.3357, 0.8629, 0.4275],
        [0.3133, 0.5064, 0.3370]])

In [127]:
 z = torch.cat([a, d], axis=0)

In [128]:
z

tensor([[0.0684, 0.3975, 0.8350],
        [0.4554, 0.6882, 0.3839],
        [0.5799, 0.9837, 0.3657],
        [0.7752, 0.7997, 0.9014],
        [0.7895, 0.8903, 0.5997],
        [0.3357, 0.8629, 0.4275],
        [0.3133, 0.5064, 0.3370]])

In [129]:
z.shape

torch.Size([7, 3])

In [ ]:
# copy a tensor

# copy a tensor

In [130]:
a = torch.rand(2, 4)

In [131]:
b = a

In [132]:
a

tensor([[0.8343, 0.5487, 0.0835, 0.2395],
        [0.4204, 0.0705, 0.3015, 0.3315]])

In [133]:
b

tensor([[0.8343, 0.5487, 0.0835, 0.2395],
        [0.4204, 0.0705, 0.3015, 0.3315]])

In [134]:
b[0][0]= 2.0

In [135]:
b

tensor([[2.0000, 0.5487, 0.0835, 0.2395],
        [0.4204, 0.0705, 0.3015, 0.3315]])

In [136]:
a

tensor([[2.0000, 0.5487, 0.0835, 0.2395],
        [0.4204, 0.0705, 0.3015, 0.3315]])

In [137]:
# clone()
a 

tensor([[2.0000, 0.5487, 0.0835, 0.2395],
        [0.4204, 0.0705, 0.3015, 0.3315]])

In [138]:
c = a.clone()

In [139]:
c

tensor([[2.0000, 0.5487, 0.0835, 0.2395],
        [0.4204, 0.0705, 0.3015, 0.3315]])

In [140]:
c[0][0]= 1.0

In [141]:
c

tensor([[1.0000, 0.5487, 0.0835, 0.2395],
        [0.4204, 0.0705, 0.3015, 0.3315]])

In [142]:
a

tensor([[2.0000, 0.5487, 0.0835, 0.2395],
        [0.4204, 0.0705, 0.3015, 0.3315]])

# basic maths operations 

In [143]:
a = torch.ones(2,3)

In [144]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [145]:
b = torch.ones(2,3)

In [146]:
c =torch.add(a, b)

In [147]:
c

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [148]:
a.add_(b)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [149]:
a

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [150]:
c = torch.sub(a, b)

In [151]:
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [154]:
c= torch.mul(a,b)

In [155]:
c

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [156]:
c = torch.div(a,b)

In [157]:
c

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [158]:
a.T

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

# send tensor to device/gpu

In [1]:
import torch

In [2]:
a = torch.rand(2,3)

In [3]:
a

tensor([[0.9839, 0.2225, 0.9731],
        [0.6062, 0.2537, 0.2494]])

In [4]:
a.device

device(type='cpu')

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [6]:
device

'cuda'

In [9]:
a=a.to(device)

In [10]:
a.device

device(type='cuda', index=0)

In [11]:
a = a.cpu().numpy()

In [12]:
a

array([[0.983929  , 0.22248602, 0.97308624],
       [0.6061656 , 0.2537431 , 0.24936014]], dtype=float32)

In [14]:
print(a)

[[0.983929   0.22248602 0.97308624]
 [0.6061656  0.2537431  0.24936014]]


In [15]:
# linear regression 

In [16]:
# 1. data prepare
# 2. model design
# 3. optimizer and loss
# 4. trining loop
#     - forward pass
#     - loss compute
#     - backward()
#     - weights update
#     - set weights to zero
# save model weights
# plot


In [17]:
x = torch.tensor([[1.],[2.],[3.],[4.]], dtype = torch.float32)
y = torch.tensor([[2.],[4.],[6.],[8.]], dtype = torch.float32)

In [35]:
w = torch.tensor(0.0,requires_grad=True, dtype = torch.float32)

In [36]:
def forward(x):
    return w*x

In [37]:
import torch.nn as nn

In [38]:
ls = nn.MSELoss()
learning_rate =0.01
optimzer = torch.optim.SGD([w], lr = learning_rate)

In [40]:
num_epochs = 10

for epoch in range(num_epochs):
    y_pred = forward(x)
    loss = ls(y_pred, y)

    loss.backward()

    optimzer.step()
    optimzer.zero_grad()

    print(f'epoch {epoch}, loss = {loss}')
    

epoch 0, loss = 21.674999237060547
epoch 1, loss = 9.832687377929688
epoch 2, loss = 7.104117393493652
epoch 3, loss = 5.132724761962891
epoch 4, loss = 3.7083935737609863
epoch 5, loss = 2.679313898086548
epoch 6, loss = 1.9358046054840088
epoch 7, loss = 1.3986183404922485
epoch 8, loss = 1.010501503944397
epoch 9, loss = 0.730087399482727


In [41]:
x = torch.tensor([[1.],[2.],[3.],[4.]], dtype = torch.float32)
y = torch.tensor([[2.],[4.],[6.],[8.]], dtype = torch.float32)

In [43]:
n_samples, n_features = x.shape

In [44]:
print(n_samples, n_features)

4 1


In [45]:
input_size = n_features
output_size = 1

In [46]:
model= nn.Linear(input_size, output_size)

In [47]:
ls = nn.MSELoss()
learning_rate =0.01
optimzer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [48]:
num_epochs = 10

for epoch in range(num_epochs):
    y_pred = model(x)
    loss = ls(y_pred, y)

    loss.backward()

    optimzer.step()
    optimzer.zero_grad()

    print(f'epoch {epoch}, loss = {loss}')
    

epoch 0, loss = 49.14412307739258
epoch 1, loss = 34.10009765625
epoch 2, loss = 23.661361694335938
epoch 3, loss = 16.41814422607422
epoch 4, loss = 11.392229080200195
epoch 5, loss = 7.904853820800781
epoch 6, loss = 5.485036849975586
epoch 7, loss = 3.805976629257202
epoch 8, loss = 2.640911817550659
epoch 9, loss = 1.8324980735778809


In [95]:
# linear regression

import torch 
import torch.nn as nn
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [96]:
x_numpy, y_numpy = make_regression(n_samples =100, n_features= 1)

In [97]:
x_numpy.min()

-2.1805259097024807

In [98]:
x_numpy.max()

2.564904920514527

In [99]:
train_x, test_x, train_y, test_y = train_test_split(x_numpy, y_numpy, test_size=0.1, random_state=42)

In [100]:
tensor_x = torch.as_tensor(train_x, dtype=torch.float32)
test_x = torch.as_tensor(test_x, dtype=torch.float32)
train_y = torch.as_tensor(train_y, dtype=torch.float32)
test_y = torch.as_tensor(test_y, dtype=torch.float32)

In [101]:
type(tensor_x)

torch.Tensor

In [102]:
n_samples, n_features = tensor_x.shape

In [103]:
n_samples

90

In [82]:
n_features

1

In [104]:
tensor_x.shape

torch.Size([90, 1])

In [105]:
train_y.shape

torch.Size([90])

In [106]:
train_y = train_y.view(train_y.shape[0], 1)

In [107]:
train_y.shape

torch.Size([90, 1])

In [111]:
# custom model 

class linearregression(nn.Module):
    def __init__(self, input_size, output_size):
        super(linearregression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        out = self.linear(x)
        return out

model = linearregression(input_size =n_features, output_size =1)

In [112]:
ls = nn.MSELoss()
learning_rate =0.01
optimzer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [113]:
num_epochs = 10

for epoch in range(num_epochs):
    y_pred = model(tensor_x)
    #print(y_pred.shape)
    loss = ls(y_pred, train_y)

    loss.backward()

    optimzer.step()
    optimzer.zero_grad()

    print(f'epoch {epoch}, loss = {loss}')
    

epoch 0, loss = 714.1205444335938
epoch 1, loss = 688.9892578125
epoch 2, loss = 664.7474975585938
epoch 3, loss = 641.3637084960938
epoch 4, loss = 618.8071899414062
epoch 5, loss = 597.0485229492188
epoch 6, loss = 576.059326171875
epoch 7, loss = 555.8120727539062
epoch 8, loss = 536.2806396484375
epoch 9, loss = 517.4393920898438


In [116]:
# custom data loader
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader,random_split
import numpy as np
import math

In [ ]:
class winedataset(Dataset):
    def __init__(self):
        ##data loading
        xy = np.loadtxt("/kaggle/input/wine-dataset/wine.csv", delimiter=',', dtype=np.float32, skiprows=1)
        self.x =torch.from_numpy(xy[:, 1:])
        self.y=torch.from_numpy(xy[:,0]).long() - 1   # n_samples, 1 , PyTorch's CrossEntropyLoss expects integer class indices starting from 0).
        print(torch.unique(self.y))
        self.n_samples = xy.shape[0]

        # Normalize the features (zero mean, unit variance)
        self.x = (self.x - self.x.mean(dim=0)) / self.x.std(dim=0)
        
        self.n_samples = xy.shape[0]
        
    def __getitem__(self, index):
        ## dataset index
        return self.x[index], self.y[index]
        
    def __len__(self):
        # len(dataset)
        return self.n_samples
    
dataset  = winedataset()
#first_data = dataset[0]

# Split into training (80%) and testing (20%)

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

#features, label = first_data
#print(features, label)

train_loader = DataLoader(dataset=train_dataset, batch_size=4, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=4, shuffle=False)

In [ ]:
dataiter = iter(train_loader)
data = next(dataiter)
features, labels = data
print(features, labels)


In [ ]:
epochs =20
total_samples = len(dataset)
n_iteration = math.ceil(total_samples/4)
print(n_iteration)

In [ ]:
class logisticregression(nn.Module):
    def __init__(self, input_size, output_size):
        super(logisticregression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
        #self.softmax = nn.Softmax()
    def forward(self, x):
        l = self.linear(x)
        #out = self.softmax(l)
        return l

model = logisticregression(input_size = 13, output_size=3)

In [ ]:
loss = nn.CrossEntropyLoss()
learning_rate=0.01
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [ ]:
for epoch in range(epochs):
    for i, (inputs, labels) in enumerate(train_loader):

        y_pred = model(inputs)
        #print(y_pred.shape)
        #print(labels.shape)
        
        ls = loss(y_pred,labels )
        
        ls.backward()
        
        optimizer.step()
        optimizer.zero_grad()
    if epoch % 1==0:
            print(f'epoch {epoch}, loss = {ls}')
        

In [ ]:
# Calculate accuracy on the test data
total_correct_test = 0
total_test_samples = 0
with torch.no_grad():
    for inputs, labels in test_loader:
        y_pred_test = torch.argmax(model(inputs), dim=1)  # Get class predictions
        total_correct_test += (y_pred_test == labels).sum().item()
        total_test_samples += labels.size(0)

    test_accuracy = total_correct_test / total_test_samples

print(f"Train Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")