## NumPy

In [2]:
import numpy as np

In [4]:
x = np.arange(16)

In [6]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
type(x)

numpy.ndarray

In [10]:
x.size

16

In [12]:
x.shape

(16,)

In [14]:
x1 = x.reshape(4,4)

In [16]:
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
x.reshape(3,3)

ValueError: cannot reshape array of size 16 into shape (3,3)

In [20]:
x3 = x.reshape(2,2,4)
x3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [22]:
x2

NameError: name 'x2' is not defined

In [24]:
print(x1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
x1[2,2]

10

In [30]:
x1[1:,::2] = -99
x1

array([[  0,   1,   2,   3],
       [-99,   5, -99,   7],
       [-99,   9, -99,  11],
       [-99,  13, -99,  15]])

In [32]:
x1.max()

15

In [34]:
x1

array([[  0,   1,   2,   3],
       [-99,   5, -99,   7],
       [-99,   9, -99,  11],
       [-99,  13, -99,  15]])

In [40]:
x1.max(axis=0)

array([ 0, 13,  2, 15])

In [42]:
x1.max(axis=1)

array([ 3,  7, 11, 15])

In [44]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
y = np.zeros((4,4))

In [50]:
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
y = np.ones((4,4))

In [54]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
z = np.empty([2,4,2])
z

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [60]:
z

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [62]:
np.full([2,3], 44)

array([[44, 44, 44],
       [44, 44, 44]])

In [64]:
ls = [22, 'python', 'location', 4.4]
arr = np.array(ls)
arr

array(['22', 'python', 'location', '4.4'], dtype='<U32')

In [66]:
z

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [68]:
z.ndim

3

In [70]:
a = np.arange(6,12,1).reshape(2,3)
a

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
b = np.arange(6,12,1).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
a*b

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [76]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [78]:
a>b

array([[False, False, False],
       [False, False, False]])

In [80]:
a+3

array([[ 9, 10, 11],
       [12, 13, 14]])

In [82]:
a

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
a[a%3==0]

array([6, 9])

In [96]:
values = np.random.randn(3,3)
values

array([[-0.30048158,  1.18613173,  0.36853581],
       [ 1.93531831, -1.32874003,  0.19818455],
       [-1.22736491, -1.51906748, -1.59125712]])

In [98]:
data = np.array([['cat', 'dog', 'cat'],['dog','dog','cat'],['cat','cat','dog']])
data

array([['cat', 'dog', 'cat'],
       ['dog', 'dog', 'cat'],
       ['cat', 'cat', 'dog']], dtype='<U3')

In [104]:
values[data=='cat']

array([-0.30048158,  0.36853581,  0.19818455, -1.22736491, -1.51906748])

In [110]:
arr = np.random.randn(10,10)
print(arr)
arr1 = np.round(arr,2)
print(arr1)

[[-0.96088787 -1.75341187 -0.75006341  0.45426998  0.37324382 -0.90795222
   0.07372288 -0.59880692  2.67558611  0.57851455]
 [ 0.61416795 -0.07217938  0.8089059  -0.56160746  1.30531722  1.70599185
  -1.11168082  0.40429933  0.41136481  0.78823834]
 [ 1.59321191 -1.30058919 -0.50759797 -0.02923583  0.25839913  0.21425836
  -0.33065351  0.96302567 -0.05774193  0.33857582]
 [ 1.17112255 -1.96816677 -1.32023201  1.26731821 -0.08479589 -1.3798068
  -1.26458899 -0.49757555 -1.24343893 -0.81475793]
 [-1.40625087 -1.2138036   1.14742669 -1.14441484  0.07418584 -0.37152548
   0.04448726  1.5518233   0.1195936  -1.1384167 ]
 [-0.44561308  0.14905005 -0.62743087  0.87156226 -0.54776314 -0.9116781
  -0.21076359 -0.01676446  1.33468693  0.5080472 ]
 [ 0.92423592 -0.2203707   0.55871586 -0.65111144  0.86148379  0.58228283
   0.29187666  0.15244318 -0.03356414  0.74271347]
 [ 1.6170575  -0.58940826 -0.71353871  0.97908573 -1.43126837 -0.60057902
  -0.0617443  -0.01730736  0.10259803  0.51888386]
 [

In [112]:
print(arr1[1:10:2])

[[ 0.61 -0.07  0.81 -0.56  1.31  1.71 -1.11  0.4   0.41  0.79]
 [ 1.17 -1.97 -1.32  1.27 -0.08 -1.38 -1.26 -0.5  -1.24 -0.81]
 [-0.45  0.15 -0.63  0.87 -0.55 -0.91 -0.21 -0.02  1.33  0.51]
 [ 1.62 -0.59 -0.71  0.98 -1.43 -0.6  -0.06 -0.02  0.1   0.52]
 [-0.68 -1.59  0.35 -0.93 -0.63 -0.46 -0.67 -1.29 -0.92  1.39]]


In [116]:
print(arr1[1:10:2,::])

[[ 0.61 -0.07  0.81 -0.56  1.31  1.71 -1.11  0.4   0.41  0.79]
 [ 1.17 -1.97 -1.32  1.27 -0.08 -1.38 -1.26 -0.5  -1.24 -0.81]
 [-0.45  0.15 -0.63  0.87 -0.55 -0.91 -0.21 -0.02  1.33  0.51]
 [ 1.62 -0.59 -0.71  0.98 -1.43 -0.6  -0.06 -0.02  0.1   0.52]
 [-0.68 -1.59  0.35 -0.93 -0.63 -0.46 -0.67 -1.29 -0.92  1.39]]


In [118]:
print(arr1[::,0:4])

[[-0.96 -1.75 -0.75  0.45]
 [ 0.61 -0.07  0.81 -0.56]
 [ 1.59 -1.3  -0.51 -0.03]
 [ 1.17 -1.97 -1.32  1.27]
 [-1.41 -1.21  1.15 -1.14]
 [-0.45  0.15 -0.63  0.87]
 [ 0.92 -0.22  0.56 -0.65]
 [ 1.62 -0.59 -0.71  0.98]
 [-0.17  0.58 -0.83 -0.76]
 [-0.68 -1.59  0.35 -0.93]]


In [120]:
x = np.array([0,1,44,3,67])
y = np.array([2,0,43,30,67])
np.maximum(x,y)

array([ 2,  1, 44, 30, 67])

In [122]:
x = np.arange(9).reshape(3,3)
print(x)
y = np.arange(6).reshape(3,2)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]


In [124]:
x*y

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [126]:
np.dot(x,y)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [128]:
x.dot(y)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [130]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [132]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [138]:
y.reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [140]:
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [142]:
y.reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [144]:
print(x)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]


In [146]:
np.concatenate((x,y),axis=1)

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3],
       [6, 7, 8, 4, 5]])

In [148]:
np.hstack((x,y))

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3],
       [6, 7, 8, 4, 5]])

In [150]:
np.vstack((x,y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

## Pandas

### Series

In [156]:
import pandas as pd

In [158]:
products = ['A','B','C','D']
products

['A', 'B', 'C', 'D']

In [160]:
type(products)

list

In [162]:
product_categories = pd.Series(products)

In [166]:
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [168]:
type(product_categories)

pandas.core.series.Series

In [172]:
start_dates_deposits = pd.Series({
    '7/4/2024': 2000,
    '1/2/2003': 3000,
    '10/4/2023': 5000
})

In [174]:
start_dates_deposits

7/4/2024     2000
1/2/2003     3000
10/4/2023    5000
dtype: int64

In [176]:
start_dates_deposits.sum()

10000

In [178]:
start_dates_deposits.min()

2000

In [180]:
start_dates_deposits.idxmin()

'7/4/2024'

In [184]:
start_dates_deposits.head(1)

7/4/2024    2000
dtype: int64

In [186]:
start_dates_deposits.tail()

7/4/2024     2000
1/2/2003     3000
10/4/2023    5000
dtype: int64

#### DataFrame

In [192]:
array_a = np.array([[3,2,1],[6,3,2]])
array_a

array([[3, 2, 1],
       [6, 3, 2]])

In [194]:
pd.DataFrame(array_a)

0  1  2
0  3  2  1
1  6  3  2

In [196]:
type(pd.DataFrame(array_a))

pandas.core.frame.DataFrame

In [200]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', 'Column 3'])
df

Column 1  Column 2  Column 3
0         3         2         1
1         6         3         2

In [206]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', 'Column 3'], index = ['Row 1', 'Row 2'])
df

Column 1  Column 2  Column 3
Row 1         3         2         1
Row 2         6         3         2

In [210]:
data = pd.read_csv('Lending-company.csv', index_col = 'LoanID')
lending_co_data = data
lending_co_data.head()

StringID    Product CustomerGender     Location    Region  TotalPrice  \
LoanID                                                                          
1       LoanID_1  Product B         Female   Location 3  Region 2     17600.0   
2       LoanID_2  Product D         Female   Location 6  Region 6         NaN   
3       LoanID_3  Product B           Male   Location 8  Region 3     16600.0   
4       LoanID_4  Product A           Male  Location 26  Region 2     17600.0   
5       LoanID_5  Product B         Female  Location 34  Region 3     21250.0   

         StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
LoanID                                                                      
1       04/07/2018     2200         45          365       3221       4166   
2       02/01/2019     2200         45          365       3161       4096   
3       08/12/2016     1000         45          365       2260       3205   
4              NaN     2200         45          365       3141       4166   
5       28/10/2017     2200         55          365       3570       4745   

        AmtPaid360 LoanStatus  
LoanID                         
1            14621     Active  
2            16041     Active  
3            16340        NaN  
4            16321     Active  
5            14720     Active

In [212]:
lending_co_data.index

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043],
      dtype='int64', name='LoanID', length=1043)

In [214]:
lending_co_data.columns

Index(['StringID', 'Product', 'CustomerGender', 'Location', 'Region',
       'TotalPrice', 'StartDate', 'Deposit', 'DailyRate', 'TotalDaysYr',
       'AmtPaid36', 'AmtPaid60', 'AmtPaid360', 'LoanStatus'],
      dtype='object')

In [216]:
type(lending_co_data.columns)

pandas.core.indexes.base.Index

In [222]:
lending_co_data.dtypes

StringID           object
Product            object
CustomerGender     object
Location           object
Region             object
TotalPrice        float64
StartDate          object
Deposit             int64
DailyRate           int64
TotalDaysYr         int64
AmtPaid36           int64
AmtPaid60           int64
AmtPaid360          int64
LoanStatus         object
dtype: object

In [224]:
lending_co_data.values

array([['LoanID_1', 'Product B', 'Female', ..., 4166, 14621, 'Active'],
       ['LoanID_2', 'Product D', 'Female', ..., 4096, 16041, 'Active'],
       ['LoanID_3', 'Product B', 'Male', ..., 3205, 16340, nan],
       ...,
       ['LoanID_1041', 'Product A', 'NotSpecified', ..., 5143, 16617,
        'Finished Payment'],
       ['LoanID_1042', 'Product B', 'Female', ..., 3462, 15617,
        'Finished Payment'],
       ['LoanID_1043', 'Product A', 'NotSpecified', ..., 4743, 16617,
        'Finished Payment']], dtype=object)

In [226]:
lending_co_data.values.shape

(1043, 14)

In [228]:
lending_co_data.to_numpy()

array([['LoanID_1', 'Product B', 'Female', ..., 4166, 14621, 'Active'],
       ['LoanID_2', 'Product D', 'Female', ..., 4096, 16041, 'Active'],
       ['LoanID_3', 'Product B', 'Male', ..., 3205, 16340, nan],
       ...,
       ['LoanID_1041', 'Product A', 'NotSpecified', ..., 5143, 16617,
        'Finished Payment'],
       ['LoanID_1042', 'Product B', 'Female', ..., 3462, 15617,
        'Finished Payment'],
       ['LoanID_1043', 'Product A', 'NotSpecified', ..., 4743, 16617,
        'Finished Payment']], dtype=object)

In [230]:
ls

[22, 'python', 'location', 4.4]

In [232]:
len(ls)

4

In [236]:
len(lending_co_data.columns)

14

In [238]:
data = pd.read_csv('Lending-company.csv', index_col = 'StringID')
lending_co_data = data
lending_co_data.head()

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_2       2  Product D         Female   Location 6  Region 6         NaN   
LoanID_3       3  Product B           Male   Location 8  Region 3     16600.0   
LoanID_4       4  Product A           Male  Location 26  Region 2     17600.0   
LoanID_5       5  Product B         Female  Location 34  Region 3     21250.0   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_2  02/01/2019     2200         45          365       3161       4096   
LoanID_3  08/12/2016     1000         45          365       2260       3205   
LoanID_4         NaN     2200         45          365       3141       4166   
LoanID_5  28/10/2017     2200         55          365       3570       4745   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_2       16041     Active  
LoanID_3       16340        NaN  
LoanID_4       16321     Active  
LoanID_5       14720     Active

In [250]:
#Not recommended
lendinag_co_data.Product

NameError: name 'lendinag_co_data' is not defined

In [252]:
# Conventional way to retrieve columns
lending_co_data['Product']

StringID
LoanID_1       Product B
LoanID_2       Product D
LoanID_3       Product B
LoanID_4       Product A
LoanID_5       Product B
                 ...    
LoanID_1039    Product B
LoanID_1040    Product A
LoanID_1041    Product A
LoanID_1042    Product B
LoanID_1043    Product A
Name: Product, Length: 1043, dtype: object

In [256]:
lending_co_data['Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [260]:
lending_co_data[['Location', 'Product']]

Location    Product
StringID                           
LoanID_1      Location 3  Product B
LoanID_2      Location 6  Product D
LoanID_3      Location 8  Product B
LoanID_4     Location 26  Product A
LoanID_5     Location 34  Product B
...                  ...        ...
LoanID_1039  Location 73  Product B
LoanID_1040  Location 82  Product A
LoanID_1041  Location 11  Product A
LoanID_1042  Location 26  Product B
LoanID_1043  Location 94  Product A

[1043 rows x 2 columns]

In [262]:
lending_co_data[['Location', 'Product']].head()

Location    Product
StringID                        
LoanID_1   Location 3  Product B
LoanID_2   Location 6  Product D
LoanID_3   Location 8  Product B
LoanID_4  Location 26  Product A
LoanID_5  Location 34  Product B

In [266]:
lending_co_data[1]

KeyError: 1

In [270]:
lending_co_data.iloc[0]

LoanID                     1
Product            Product B
CustomerGender        Female
Location          Location 3
Region              Region 2
TotalPrice           17600.0
StartDate         04/07/2018
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3221
AmtPaid60               4166
AmtPaid360             14621
LoanStatus            Active
Name: LoanID_1, dtype: object

In [272]:
lending_co_data.head()

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_2       2  Product D         Female   Location 6  Region 6         NaN   
LoanID_3       3  Product B           Male   Location 8  Region 3     16600.0   
LoanID_4       4  Product A           Male  Location 26  Region 2     17600.0   
LoanID_5       5  Product B         Female  Location 34  Region 3     21250.0   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_2  02/01/2019     2200         45          365       3161       4096   
LoanID_3  08/12/2016     1000         45          365       2260       3205   
LoanID_4         NaN     2200         45          365       3141       4166   
LoanID_5  28/10/2017     2200         55          365       3570       4745   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_2       16041     Active  
LoanID_3       16340        NaN  
LoanID_4       16321     Active  
LoanID_5       14720     Active

In [274]:
lending_co_data.iloc[1,3]

'Location 6'

In [276]:
lending_co_data.iloc[:,3]

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [278]:
lending_co_data

LoanID    Product CustomerGender     Location    Region  \
StringID                                                               
LoanID_1          1  Product B         Female   Location 3  Region 2   
LoanID_2          2  Product D         Female   Location 6  Region 6   
LoanID_3          3  Product B           Male   Location 8  Region 3   
LoanID_4          4  Product A           Male  Location 26  Region 2   
LoanID_5          5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
LoanID_1039    1039  Product B           Male  Location 73  Region 6   
LoanID_1040    1040  Product A           Male  Location 82  Region 1   
LoanID_1041    1041  Product A   NotSpecified  Location 11  Region 4   
LoanID_1042    1042  Product B         Female  Location 26  Region 6   
LoanID_1043    1043  Product A   NotSpecified  Location 94  Region 6   

             TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  \
StringID                                                               
LoanID_1        17600.0  04/07/2018     2200         45          365   
LoanID_2            NaN  02/01/2019     2200         45          365   
LoanID_3        16600.0  08/12/2016     1000         45          365   
LoanID_4        17600.0         NaN     2200         45          365   
LoanID_5        21250.0  28/10/2017     2200         55          365   
...                 ...         ...      ...        ...          ...   
LoanID_1039     17300.0  29/12/2018     2200         45          365   
LoanID_1040         NaN  28/03/2018     2200         45          365   
LoanID_1041     17300.0  26/04/2018     2200         45          365   
LoanID_1042     16300.0  25/10/2016     1000         45          365   
LoanID_1043     17300.0  15/05/2019     2200         45          365   

             AmtPaid36  AmtPaid60  AmtPaid360        LoanStatus  
StringID                                                         
LoanID_1          3221       4166       14621            Active  
LoanID_2          3161       4096       16041            Active  
LoanID_3          2260       3205       16340               NaN  
LoanID_4          3141       4166       16321            Active  
LoanID_5          3570       4745       14720            Active  
...                ...        ...         ...               ...  
LoanID_1039       3251       4743       16617  Finished Payment  
LoanID_1040       4090       5582       16617  Finished Payment  
LoanID_1041       4051       5143       16617  Finished Payment  
LoanID_1042       1930       3462       15617  Finished Payment  
LoanID_1043       4451       4743       16617  Finished Payment  

[1043 rows x 14 columns]

In [280]:
lending_co_data.loc['LoanID_3']

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [282]:
lending_co_data.loc['LoanID_3':]

LoanID    Product CustomerGender     Location    Region  \
StringID                                                               
LoanID_3          3  Product B           Male   Location 8  Region 3   
LoanID_4          4  Product A           Male  Location 26  Region 2   
LoanID_5          5  Product B         Female  Location 34  Region 3   
LoanID_6          6  Product A           Male  Location 34  Region 1   
LoanID_7          7  Product A           Male  Location 25       NaN   
...             ...        ...            ...          ...       ...   
LoanID_1039    1039  Product B           Male  Location 73  Region 6   
LoanID_1040    1040  Product A           Male  Location 82  Region 1   
LoanID_1041    1041  Product A   NotSpecified  Location 11  Region 4   
LoanID_1042    1042  Product B         Female  Location 26  Region 6   
LoanID_1043    1043  Product A   NotSpecified  Location 94  Region 6   

             TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  \
StringID                                                               
LoanID_3        16600.0  08/12/2016     1000         45          365   
LoanID_4        17600.0         NaN     2200         45          365   
LoanID_5        21250.0  28/10/2017     2200         55          365   
LoanID_6            NaN  19/04/2019     2200         45          365   
LoanID_7        21250.0  04/07/2020     2200         55          365   
...                 ...         ...      ...        ...          ...   
LoanID_1039     17300.0  29/12/2018     2200         45          365   
LoanID_1040         NaN  28/03/2018     2200         45          365   
LoanID_1041     17300.0  26/04/2018     2200         45          365   
LoanID_1042     16300.0  25/10/2016     1000         45          365   
LoanID_1043     17300.0  15/05/2019     2200         45          365   

             AmtPaid36  AmtPaid60  AmtPaid360        LoanStatus  
StringID                                                         
LoanID_3          2260       3205       16340               NaN  
LoanID_4          3141       4166       16321            Active  
LoanID_5          3570       4745       14720            Active  
LoanID_6          3301       4066       15141            Active  
LoanID_7          1951       3176       18701            Active  
...                ...        ...         ...               ...  
LoanID_1039       3251       4743       16617  Finished Payment  
LoanID_1040       4090       5582       16617  Finished Payment  
LoanID_1041       4051       5143       16617  Finished Payment  
LoanID_1042       1930       3462       15617  Finished Payment  
LoanID_1043       4451       4743       16617  Finished Payment  

[1041 rows x 14 columns]

In [284]:
lending_co_data.iloc[5:10,:]

LoanID    Product CustomerGender      Location    Region  \
StringID                                                              
LoanID_6        6  Product A           Male   Location 34  Region 1   
LoanID_7        7  Product A           Male   Location 25       NaN   
LoanID_8        8  Product D           Male   Location 46  Region 5   
LoanID_9        9  Product A           Male  Location 156  Region 6   
LoanID_10      10  Product C           Male   Location 21  Region 9   

           TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
StringID                                                                        
LoanID_6          NaN  19/04/2019     2200         45          365       3301   
LoanID_7      21250.0  04/07/2020     2200         55          365       1951   
LoanID_8      17600.0  24/04/2018     2200         45          365       4071   
LoanID_9      23250.0  03/09/2019     5000         55          365       5850   
LoanID_10     21250.0  25/07/2020     2200         55          365       2051   

           AmtPaid60  AmtPaid360 LoanStatus  
StringID                                     
LoanID_6        4066       15141     Active  
LoanID_7        3176       18701     Active  
LoanID_8        4056       16351     Active  
LoanID_9        7375       21250        NaN  
LoanID_10       3176       18351     Active

In [288]:
lending_co_data.loc['LoanID_5':'LoanID_10',:]

LoanID    Product CustomerGender      Location    Region  \
StringID                                                              
LoanID_5        5  Product B         Female   Location 34  Region 3   
LoanID_6        6  Product A           Male   Location 34  Region 1   
LoanID_7        7  Product A           Male   Location 25       NaN   
LoanID_8        8  Product D           Male   Location 46  Region 5   
LoanID_9        9  Product A           Male  Location 156  Region 6   
LoanID_10      10  Product C           Male   Location 21  Region 9   

           TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
StringID                                                                        
LoanID_5      21250.0  28/10/2017     2200         55          365       3570   
LoanID_6          NaN  19/04/2019     2200         45          365       3301   
LoanID_7      21250.0  04/07/2020     2200         55          365       1951   
LoanID_8      17600.0  24/04/2018     2200         45          365       4071   
LoanID_9      23250.0  03/09/2019     5000         55          365       5850   
LoanID_10     21250.0  25/07/2020     2200         55          365       2051   

           AmtPaid60  AmtPaid360 LoanStatus  
StringID                                     
LoanID_5        4745       14720     Active  
LoanID_6        4066       15141     Active  
LoanID_7        3176       18701     Active  
LoanID_8        4056       16351     Active  
LoanID_9        7375       21250        NaN  
LoanID_10       3176       18351     Active

In [290]:
lending_co_data.loc['LoanID_8','TotalPrice']

17600.0

In [292]:
lending_co_data.loc[:,'TotalPrice']

StringID
LoanID_1       17600.0
LoanID_2           NaN
LoanID_3       16600.0
LoanID_4       17600.0
LoanID_5       21250.0
                ...   
LoanID_1039    17300.0
LoanID_1040        NaN
LoanID_1041    17300.0
LoanID_1042    16300.0
LoanID_1043    17300.0
Name: TotalPrice, Length: 1043, dtype: float64

In [298]:
array_a

array([[3, 2, 1],
       [6, 3, 2]])

In [302]:
arr = array_a.flatten()

In [304]:
arr

array([3, 2, 1, 6, 3, 2])

In [306]:
for i in arr:
    print(i)

3
2
1
6
3
2


In [308]:
for idx, ele in arr:
    print(idx, ele)

TypeError: cannot unpack non-iterable numpy.int32 object

In [310]:
for idx, ele in enumerate(arr):
    print(idx, ele)

0 3
1 2
2 1
3 6
4 3
5 2


In [312]:
array_b = ['product', 'loan', 4000]
for idx, ele in enumerate(array_b):
    print(idx, ele)

0 product
1 loan
2 4000


In [324]:
array_b[2] = str(array_b[2])

In [326]:
array_b

['product', 'loan', '4000']

In [330]:
with open('file1.txt', 'w') as f1:
    f1.writelines(array_b)

In [338]:
with open('file1.txt', 'w') as f1:
    for i in array_b:
        f1.writelines(i+'\n')

In [352]:
with open('file1.txt', 'r') as f1:
    contents = f1.read()

In [354]:
contents

'product\nloan\n4000\n'